create or replace view APP_USAGE_MONTHLY_USERS(
	UNIQUE_ID,
	ORGANIZATION_ID,
	YEAR_AND_MONTH,
	USER_COUNT,
	MIN_USER_DISTINCT_DAYS,
	MAX_USER_DISTINCT_DAYS,
	AVG_USER_DISTINCT_DAYS
) as (
with user_stats as (
select ORGANIZATION_ID, date_part(year,TIMESTAMP)||'-'||lpad(date_part(month,TIMESTAMP),2,'0') as YEAR_AND_MONTH,USER_ID_TOKEN,count(distinct to_char(TIMESTAMP, 'YYYY-MM-DD')) distinct_days
from APP_USAGE
group by ORGANIZATION_ID, YEAR_AND_MONTH, USER_ID_TOKEN
)
select HASH(ORGANIZATION_ID||'|'||YEAR_AND_MONTH) as UNIQUE_ID, ORGANIZATION_ID::varchar(255) as ORGANIZATION_ID,YEAR_AND_MONTH::varchar(255) as YEAR_AND_MONTH,COUNT(USER_ID_TOKEN) as USER_COUNT,MIN(DISTINCT_DAYS) as MIN_USER_DISTINCT_DAYS,MAX(DISTINCT_DAYS) as MAX_USER_DISTINCT_DAYS,AVG(DISTINCT_DAYS) as AVG_USER_DISTINCT_DAYS 
from user_stats
group by ORGANIZATION_ID,YEAR_AND_MONTH
 ORDER BY ORGANIZATION_ID,YEAR_AND_MONTH
);
